/** One-off hand-matched map from Daily Strength exercise names to built-in library ids; null stays custom. */
export const DAILY_STRENGTH_LIBRARY: Readonly<Record<string, string | null>> = {
  'Alternating Dumbbell Bicep Curls': 'bicep-curl',
  'Barbell Bench Press': 'bench-press',
  'Barbell Bicep Curl': 'ez-bar-curl',
  'Barbell Deadlifts': 'deadlift',
  'Barbell Front Squat': 'front-squat',
  'Barbell Glute Bridge': 'barbell-glute-bridge',
  'Barbell Hip Thrust': 'hip-thrust',
  'Barbell Preacher Curl': 'preacher-curl',
  'Barbell Romanian Deadlift': 'romanian-deadlift',
  'Barbell Squat': 'squat',
  'Bicep Curl Machine': 'preacher-curl',
  'Butterfly Machine (Pec Deck)': 'pec-deck',
  'Cable Bicep Curl': 'cable-curl',
  'Cable Crossover': 'cable-fly',
  'Cable Rope Triceps Pushdown': 'rope-tricep-pushdown',
  'Cable Seated Crunch': 'cable-crunch',
  'Cable Triceps Pushdown': 'tricep-pushdown',
  'Calf Press On Leg Press': 'leg-press-calf-raise',
  'Chest Dips': 'chest-dip',
  'Chest Press Machine': 'machine-chest-press',
  'Close Grip Barbell Bench Press': 'close-grip-bench-press',
  'Close Grip Lat Pulldown': 'close-grip-lat-pulldown',
  'Decline Crunch': 'crunch',
  'Dumbbell Bench Press': 'dumbbell-bench-press',
  'Dumbbell Bicep Curl': 'bicep-curl',
  'Dumbbell Bulgarian Split Squat': 'bulgarian-split-squat',
  'Dumbbell Hammer Curls': 'hammer-curl',
  'Dumbbell Shoulder Press': 'seated-dumbbell-press',
  'Dumbbell Walking Lunges': 'walking-lunge',
  'EZ Bar Curl': 'ez-bar-curl',
  'Face Pull': 'face-pull',
  'Hack Squat Machine': 'hack-squat',
  'Incline Barbell Bench Press': 'incline-bench-press',
  'Incline Chest Press Machine': 'machine-chest-press',
  'Incline Dumbbell Bench Press': 'incline-dumbbell-press',
  'Incline Dumbbell Bicep Curls': 'incline-dumbbell-curl',
  'Lateral Dumbbell Raises': 'lateral-raise',
  'Leg Extensions': 'leg-extension',
  'Leg Press': 'leg-press',
  'Lying Dumbbell Triceps Extension (Skull Crusher)': 'dumbbell-skull-crusher',
  'Lying Leg Curl': 'lying-leg-curl',
  'One Arm Cable Lateral Raise': 'cable-lateral-raise',
  'One Arm Low Pulley Cable Triceps Extension': null,
  'Preacher Curl Machine': 'preacher-curl',
  'Pull Ups': 'pull-up',
  'Pull over': null,
  'Reverse Fly Machine': 'reverse-pec-deck',
  'Seated Cable Rows': 'seated-row',
  'Seated Calf Raise Machine': 'seated-calf-raise',
  'Seated Leg Curl': 'seated-leg-curl',
  'Seated Row Machine': 'machine-row',
  'Seated Shoulder Press Machine': 'machine-shoulder-press',
  'Seated Single Arm Cable Rows': 'single-arm-cable-row',
  'Seated Triceps Dip Machine': null,
  'Single arm Row': 'one-arm-dumbbell-row',
  'Smith Machine Deadlifts': 'deadlift',
  'Smith Machine Squats': 'smith-machine-squat',
  'Standing Barbell Military Press': 'overhead-press',
  'Standing Cable Reverse Fly': 'cable-rear-delt-fly',
  'Standing Calf Raise Machine': 'standing-calf-raise',
  'Straight Arm Cable Lat Pulldown': 'straight-arm-pulldown',
  'T-Bar Rows': 't-bar-row',
  'Thigh Abductor': 'hip-abduction-machine',
  'Triceps Extension Machine': null,
  'Wide Grip Lat Pull Down': 'wide-grip-lat-pulldown',
};
