import assert from 'node:assert/strict';
import { test } from 'node:test';

import { matchArtKey } from './exercise-art-match.ts';

const ART_KEYS = [
  'bench-press',
  'incline-bench-press',
  'incline-dumbbell-press',
  'dumbbell-bench-press',
  'decline-bench-press',
  'machine-chest-press',
  'pec-deck',
  'cable-fly',
  'push-up',
  'weighted-push-up',
  'overhead-press',
  'seated-dumbbell-press',
  'arnold-press',
  'lateral-raise',
  'cable-lateral-raise',
  'front-raise',
  'rear-delt-fly',
  'reverse-pec-deck',
  'face-pull',
  'upright-row',
  'deadlift',
  'romanian-deadlift',
  'barbell-row',
  't-bar-row',
  'dumbbell-bent-over-row',
  'one-arm-dumbbell-row',
  'chest-supported-row',
  'seated-row',
  'machine-row',
  'lat-pulldown',
  'close-grip-lat-pulldown',
  'straight-arm-pulldown',
  'pull-up',
  'assisted-pull-up',
  'weighted-pull-up',
  'chin-up',
  'shrug',
  'squat',
  'front-squat',
  'hack-squat',
  'leg-press',
  'bulgarian-split-squat',
  'walking-lunge',
  'step-up',
  'leg-extension',
  'leg-curl',
  'seated-leg-curl',
  'hip-thrust',
  'glute-bridge',
  'good-morning',
  'standing-calf-raise',
  'seated-calf-raise',
  'bicep-curl',
  'hammer-curl',
  'preacher-curl',
  'cable-curl',
  'reverse-curl',
  'wrist-curl',
  'tricep-pushdown',
  'overhead-tricep-extension',
  'skull-crusher',
  'close-grip-bench-press',
  'dip',
  'assisted-dip',
  'plank',
  'side-plank',
  'hanging-leg-raise',
  'cable-crunch',
  'ab-wheel',
  'running',
  'walking',
  'cycling',
  'rowing',
  'stair-climber',
  'dumbbell-fly',
  'incline-cable-fly',
  'decline-dumbbell-press',
  'smith-machine-bench-press',
  'landmine-press',
  'chest-dip',
  'weighted-dip',
  'machine-shoulder-press',
  'standing-dumbbell-press',
  'push-press',
  'machine-lateral-raise',
  'cable-front-raise',
  'plate-front-raise',
  'bent-over-rear-delt-raise',
  'cable-rear-delt-fly',
  'pendlay-row',
  'inverted-row',
  'meadows-row',
  'single-arm-cable-row',
  'wide-grip-lat-pulldown',
  'neutral-grip-pull-up',
  'assisted-chin-up',
  'weighted-chin-up',
  'rack-pull',
  'back-extension',
  'dumbbell-shrug',
  'goblet-squat',
  'smith-machine-squat',
  'belt-squat',
  'sumo-deadlift',
  'trap-bar-deadlift',
  'lying-leg-curl',
  'nordic-hamstring-curl',
  'single-leg-romanian-deadlift',
  'reverse-lunge',
  'split-squat',
  'cable-kickback',
  'hip-abduction-machine',
  'single-leg-glute-bridge',
  'barbell-glute-bridge',
  'dumbbell-glute-bridge',
  'dumbbell-hip-thrust',
  'smith-machine-hip-thrust',
  'smith-machine-romanian-deadlift',
  'dumbbell-romanian-deadlift',
  'kettlebell-romanian-deadlift',
  'cable-pull-through',
  'machine-glute-kickback',
  'cable-standing-hip-abduction',
  'cable-standing-hip-adduction',
  'hip-adduction-machine',
  'smith-machine-bulgarian-split-squat',
  'smith-machine-reverse-lunge',
  'smith-machine-split-squat',
  'heel-elevated-goblet-squat',
  'dumbbell-sumo-squat',
  'dumbbell-sumo-deadlift',
  'front-foot-elevated-split-squat',
  'deficit-reverse-lunge',
  'dumbbell-lateral-lunge',
  'dumbbell-curtsy-lunge',
  'landmine-squat',
  'landmine-romanian-deadlift',
  'kettlebell-swing',
  'glute-focused-back-extension',
  'reverse-hyperextension',
  'donkey-calf-raise',
  'leg-press-calf-raise',
  'wall-sit',
  'jump-squat',
  'incline-dumbbell-curl',
  'concentration-curl',
  'ez-bar-curl',
  'spider-curl',
  'rope-hammer-curl',
  'drag-curl',
  'rope-tricep-pushdown',
  'dumbbell-skull-crusher',
  'single-dumbbell-skullcrusher',
  'dumbbell-overhead-tricep-extension',
  'single-arm-dumbbell-tricep-extension',
  'bench-dip',
  'tricep-kickback',
  'wrist-extension',
  'farmer-carry',
  'crunch',
  'reverse-crunch',
  'russian-twist',
  'bicycle-crunch',
  'mountain-climber',
  'dead-bug',
  'bird-dog',
  'pallof-press',
  'cable-woodchop',
  'half-kneeling-pallof-press',
  'cable-pallof-hold',
  'hanging-knee-raise',
  'captains-chair-knee-raise',
  'decline-sit-up',
  'weighted-crunch',
  'weighted-russian-twist',
  'dumbbell-side-bend',
  'elliptical',
  'swimming',
  'jump-rope',
  'assault-bike',
  'skierg',
  'hiking',
  'treadmill-incline-walk',
  'battle-ropes',
  'incline-push-up',
  'knee-push-up',
  'wide-push-up',
  'diamond-push-up',
  'decline-push-up',
  'pike-push-up',
  'feet-elevated-pike-push-up',
  'archer-push-up',
  'typewriter-push-up',
  'explosive-push-up',
  'hindu-push-up',
  'scapular-push-up',
  'push-up-shoulder-tap',
  'wall-push-up',
  'wall-walk',
  'wall-handstand-push-up',
  'handstand-push-up',
  'chair-dip',
  'doorway-row',
  'towel-row',
  'prone-y-raise',
  'prone-t-raise',
  'superman',
  'superman-hold',
  'reverse-snow-angel',
  'dead-hang',
  'active-hang',
  'scapular-pull-up',
  'negative-pull-up',
  'commando-pull-up',
  'l-sit-pull-up',
  'towel-pull-up',
  'bodyweight-squat',
  'pistol-squat',
  'assisted-pistol-squat',
  'shrimp-squat',
  'cossack-squat',
  'sissy-squat',
  'forward-lunge',
  'lateral-lunge',
  'curtsy-lunge',
  'skater-squat',
  'single-leg-box-squat',
  'step-down',
  'calf-raise',
  'single-leg-calf-raise',
  'glute-bridge-march',
  'frog-pump',
  'donkey-kick',
  'fire-hydrant',
  'clamshell',
  'hip-airplane',
  'side-lying-hip-abduction',
  'side-lying-leg-raise',
  'lying-hamstring-walkout',
  'towel-hamstring-curl',
  'stability-ball-hamstring-curl',
  'banded-glute-bridge',
  'banded-hip-thrust',
  'banded-frog-pump',
  'banded-clamshell',
  'banded-lateral-walk',
  'banded-monster-walk',
  'banded-squat',
  'banded-donkey-kick',
  'banded-fire-hydrant',
  'banded-kickback',
  'banded-standing-hip-abduction',
  'banded-seated-hip-abduction',
  'band-pull-apart',
  'banded-face-pull',
  'banded-row',
  'banded-lat-pulldown',
  'banded-pallof-press',
  'banded-woodchop',
  'banded-dead-bug',
  'hollow-body-hold',
  'hollow-rock',
  'v-up',
  'flutter-kick',
  'lying-leg-raise',
  'toe-touch',
  'heel-tap',
  'plank-shoulder-tap',
  'plank-jack',
  'bear-plank',
  'bear-crawl',
  'crab-walk',
  'inchworm',
  'l-sit-hold',
  'seated-knee-tuck',
  'side-plank-hip-dip',
  'copenhagen-plank',
  'dragon-flag',
  'burpee',
  'half-burpee',
  'squat-thrust',
  'high-knees',
  'jumping-jack',
  'skater-hop',
  'lateral-shuffle',
  'fast-feet',
  'sprawl',
  'seal-jack',
  'cat-cow-stretch',
  'arm-circles',
  'worlds-greatest-stretch',
  'leg-swings-stretch',
  'torso-twist-stretch',
  'doorway-chest-stretch',
  'childs-pose',
  'kneeling-hip-flexor-stretch',
  'hamstring-stretch',
  'standing-quad-stretch',
  'seated-forward-fold-stretch',
  'cross-body-shoulder-stretch',
  'wall-calf-stretch',
  'butterfly-stretch',
] as const;

const IMPORTED: readonly (readonly [string, string | null])[] = [
  ['Alternating Dumbbell Bicep Curls', 'bicep-curl'],
  ['Barbell Bench Press', 'bench-press'],
  ['Barbell Bicep Curl', null],
  ['Barbell Deadlifts', 'deadlift'],
  ['Barbell Front Squat', 'front-squat'],
  ['Barbell Glute Bridge', 'barbell-glute-bridge'],
  ['Barbell Hip Thrust', 'hip-thrust'],
  ['Barbell Preacher Curl', null],
  ['Barbell Romanian Deadlift', 'romanian-deadlift'],
  ['Barbell Squat', 'squat'],
  ['Bicep Curl Machine', null],
  ['Butterfly Machine (Pec Deck)', 'pec-deck'],
  ['Cable Bicep Curl', 'cable-curl'],
  ['Cable Crossover', 'cable-fly'],
  ['Cable Rope Triceps Pushdown', 'rope-tricep-pushdown'],
  ['Cable Seated Crunch', null],
  ['Cable Triceps Pushdown', 'tricep-pushdown'],
  ['Calf Press On Leg Press', 'leg-press-calf-raise'],
  ['Chest Dips', 'chest-dip'],
  ['Chest Press Machine', 'machine-chest-press'],
  ['Close Grip Barbell Bench Press', 'close-grip-bench-press'],
  ['Close Grip Lat Pulldown', 'close-grip-lat-pulldown'],
  ['Decline Crunch', null],
  ['Dumbbell Bench Press', 'dumbbell-bench-press'],
  ['Dumbbell Bicep Curl', 'bicep-curl'],
  ['Dumbbell Bulgarian Split Squat', 'bulgarian-split-squat'],
  ['Dumbbell Hammer Curls', 'hammer-curl'],
  ['Dumbbell Shoulder Press', 'seated-dumbbell-press'],
  ['Dumbbell Walking Lunges', 'walking-lunge'],
  ['EZ Bar Curl', 'ez-bar-curl'],
  ['Face Pull', 'face-pull'],
  ['Hack Squat Machine', 'hack-squat'],
  ['Incline Barbell Bench Press', 'incline-bench-press'],
  ['Incline Chest Press Machine', null],
  ['Incline Dumbbell Bench Press', 'incline-dumbbell-press'],
  ['Incline Dumbbell Bicep Curls', 'incline-dumbbell-curl'],
  ['Lateral Dumbbell Raises', 'lateral-raise'],
  ['Leg Extensions', 'leg-extension'],
  ['Leg Press', 'leg-press'],
  ['Lying Dumbbell Triceps Extension (Skull Crusher)', 'dumbbell-skull-crusher'],
  ['Lying Leg Curl', 'lying-leg-curl'],
  ['One Arm Cable Lateral Raise', 'cable-lateral-raise'],
  ['One Arm Low Pulley Cable Triceps Extension', null],
  ['Preacher Curl Machine', 'preacher-curl'],
  ['Pull Ups', 'pull-up'],
  ['Pull over', null],
  ['Reverse Fly Machine', 'reverse-pec-deck'],
  ['Seated Cable Rows', 'seated-row'],
  ['Seated Calf Raise Machine', 'seated-calf-raise'],
  ['Seated Leg Curl', 'seated-leg-curl'],
  ['Seated Row Machine', 'machine-row'],
  ['Seated Shoulder Press Machine', 'machine-shoulder-press'],
  ['Seated Single Arm Cable Rows', 'single-arm-cable-row'],
  ['Seated Triceps Dip Machine', null],
  ['Single arm Row', null],
  ['Smith Machine Deadlifts', null],
  ['Smith Machine Squats', 'smith-machine-squat'],
  ['Standing Barbell Military Press', 'overhead-press'],
  ['Standing Cable Reverse Fly', 'cable-rear-delt-fly'],
  ['Standing Calf Raise Machine', 'standing-calf-raise'],
  ['Straight Arm Cable Lat Pulldown', 'straight-arm-pulldown'],
  ['T-Bar Rows', 't-bar-row'],
  ['Thigh Abductor', 'hip-abduction-machine'],
  ['Triceps Extension Machine', null],
  ['Wide Grip Lat Pull Down', 'wide-grip-lat-pulldown'],
];

for (const [name, key] of IMPORTED) {
  test(`imported exercise: ${name} -> ${key ?? 'UNMATCHED'}`, () => {
    assert.equal(matchArtKey(name, ART_KEYS), key);
  });
}

test('normalizes case, punctuation, whitespace and simple plurals', () => {
  assert.equal(matchArtKey('  DUMBBELL—BENCH   PRESSES!! ', ART_KEYS), 'dumbbell-bench-press');
  assert.equal(matchArtKey('  Seated / Cable ROWS ', ART_KEYS), 'seated-row');
  assert.equal(matchArtKey('Butterfly Machine [Pec Deck]', ART_KEYS), 'pec-deck');
  assert.equal(matchArtKey('PULL-UPS', ART_KEYS), 'pull-up');
  assert.equal(matchArtKey('Cable Rope Triceps Pushdown', ART_KEYS), 'rope-tricep-pushdown');
});

test('matches every library slug exactly', () => {
  for (const key of ART_KEYS) assert.equal(matchArtKey(key, ART_KEYS), key, key);
});

test('only returns keys available in the supplied library', () => {
  assert.equal(matchArtKey('Barbell Bench Press', []), null);
  assert.equal(matchArtKey('Dumbbell Bench Press', ['bench-press']), null);
  assert.equal(matchArtKey('Chest Press Machine', ['bench-press']), null);
  assert.equal(matchArtKey('Barbell Bicep Curl', ['bicep-curl', 'ez-bar-curl']), null);
  assert.equal(matchArtKey('Barbell Preacher Curl', ['preacher-curl']), null);
  assert.equal(matchArtKey('Wide Grip Lat Pull Down', ['lat-pulldown']), null);
});

test('does not discard movement, implement, or variant qualifiers to guess art', () => {
  for (const name of [
    'Machine Bench Press',
    'Cable Bench Press',
    'Kettlebell Bench Press',
    'Dumbbell Romanian Deadlift Machine',
    'Incline Chest Press Machine',
    'Barbell Bench Press Reverse Grip',
    'Assisted Chest Dips',
    'Single Arm Row',
    'Bench',
    'Press',
    '',
    '   !!! ',
    'constructor',
    'toString',
  ])
    assert.equal(matchArtKey(name, ART_KEYS), null, name);
});

test('prioritizes an exact slug over an alias', () => {
  assert.equal(
    matchArtKey('Barbell Bench Press', ['barbell-bench-press', 'bench-press']),
    'barbell-bench-press',
  );
});
