#!/usr/bin/env node
/**
 * Generate src/components/body-map/paths.ts from the vendored MuscleMap art in
 * assets/bodymap/ (see claudedocs/body-map.md). Run by hand, commit the output.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { MALE_FRONT } = await import(join(root, 'assets/bodymap/male-front.ts'));
const { MALE_BACK } = await import(join(root, 'assets/bodymap/male-back.ts'));

const MAP = {
  CHEST: 'chest',
  BACK_UPPER: 'back',
  RHOMBOIDS: 'back',
  BACK_LOWER: 'lower_back',
  TRAPEZIUS: 'traps',
  LATS: 'lats',
  SHOULDERS_FRONT: 'shoulders',
  SHOULDERS_SIDE: 'shoulders',
  SHOULDERS_REAR: 'shoulders',
  BICEPS: 'biceps',
  TRICEPS: 'triceps',
  FOREARMS: 'forearms',
  CORE: 'abs',
  OBLIQUES: 'abs',
  GLUTES: 'glutes',
  ABDUCTORS: 'glutes',
  QUADS: 'quads',
  HAMSTRINGS: 'hamstrings',
  CALVES: 'calves',
  ADDUCTORS: 'adductors',
};

const view = (d) => ({
  outline: d.outline.map((o) => o.d),
  surfaces: d.muscles.flatMap((m) => {
    if (m.group === 'HIP_FLEXORS') return [];
    const muscle = MAP[m.group];
    if (!muscle) throw new Error(`unmapped group ${m.group}`);
    return [{ muscle, d: m.d }];
  }),
});

const body = { front: view(MALE_FRONT), back: view(MALE_BACK) };

const out = `// Generated by scripts/build-bodymap.mjs from assets/bodymap/ — do not edit.
// Source: github.com/Jsplice/MuscleMap packages/assets (MIT, see assets/bodymap/LICENSE).
import type { Muscle } from '@/data/schema';

export const BODY_VIEWBOX = { w: 1024, h: 1536 } as const;

export const BODY: Record<
  'front' | 'back',
  { outline: string[]; surfaces: { muscle: Muscle; d: string }[] }
> = ${JSON.stringify(body, null, 2)};
`;
writeFileSync(join(root, 'src/components/body-map/paths.ts'), out);
console.log(
  Object.entries(body)
    .map(([k, v]) => `${k}: ${v.outline.length} outline, ${v.surfaces.length} surfaces`)
    .join('\n'),
);
