#!/usr/bin/env node
/**
 * Generate drizzle/0001_seed_exercises.sql from free-exercise-db.
 *
 * Source: https://github.com/yuhonas/free-exercise-db (Unlicense / public domain).
 * Text only — the design has excluded photography since round one, so `images`
 * is ignored entirely.
 *
 * Run with --offline to use a previously downloaded cache.
 */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json';
const CACHE = join(root, 'node_modules', '.cache-free-exercise-db.json');

/** Fixed: a migration whose bytes change on every run is a broken migration. */
const STAMP = 1788745400000;

/** Categories a strength trainee actually logs. Stretching and cardio are not lifts. */
const KEEP = new Set(['strength', 'powerlifting', 'olympic weightlifting', 'strongman']);

/** Their equipment vocabulary onto our six. */
const EQUIPMENT = {
  'barbell': 'barbell',
  'e-z curl bar': 'barbell',
  'dumbbell': 'dumbbell',
  'kettlebells': 'dumbbell',   // a free weight held in the hand; loads like one
  'machine': 'machine',
  'cable': 'cable',
  'body only': 'bodyweight',
  'bands': 'other',
  'medicine ball': 'other',
  'exercise ball': 'other',
  'foam roll': 'other',
  'other': 'other',
};

/** Their muscle vocabulary onto the sixteen in schema.ts. */
const MUSCLE = {
  quadriceps: 'quads', hamstrings: 'hamstrings', glutes: 'glutes', calves: 'calves',
  adductors: 'adductors', chest: 'chest', 'middle back': 'back', lats: 'lats',
  traps: 'traps', 'lower back': 'lower_back', shoulders: 'shoulders', biceps: 'biceps',
  triceps: 'triceps', forearms: 'forearms', abdominals: 'abs', neck: 'neck',
  // abductors has no home in our sixteen; dropped rather than inventing a muscle.
};

const slug = (name) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const q = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

async function load() {
  if (process.argv.includes('--offline') && existsSync(CACHE)) {
    return JSON.parse(readFileSync(CACHE, 'utf8'));
  }
  const res = await fetch(SRC);
  if (!res.ok) throw new Error(`${SRC} → HTTP ${res.status}`);
  const json = await res.json();
  writeFileSync(CACHE, JSON.stringify(json));
  return json;
}

const raw = await load();
const dropped = { category: 0, noMuscle: 0, noInstructions: 0, collision: 0 };
const droppedMuscles = new Map();
const seen = new Map();
const rows = [];

for (const e of raw) {
  if (!KEEP.has(e.category)) { dropped.category++; continue; }
  if (!e.instructions?.length) { dropped.noInstructions++; continue; }

  const muscles = [];
  const add = (list, role) => {
    for (const m of list ?? []) {
      const mapped = MUSCLE[m];
      if (!mapped) { droppedMuscles.set(m, (droppedMuscles.get(m) ?? 0) + 1); continue; }
      if (!muscles.some((x) => x.muscle === mapped)) muscles.push({ muscle: mapped, role });
    }
  };
  add(e.primaryMuscles, 'prime');
  add(e.secondaryMuscles, 'assist');
  if (!muscles.length) { dropped.noMuscle++; continue; }

  const id = slug(e.name);
  if (seen.has(id)) { dropped.collision++; continue; }
  seen.set(id, e.name);

  const equipment = EQUIPMENT[e.equipment] ?? 'other';
  // mechanic is null on 87 records. An olympic/power/strongman lift is compound by
  // definition; otherwise a single muscle with no assistance is the isolation case.
  const kind =
    e.mechanic ??
    (e.category !== 'strength'
      ? 'compound'
      : (e.primaryMuscles?.length ?? 0) === 1 && !(e.secondaryMuscles?.length)
        ? 'isolation'
        : 'compound');

  rows.push({
    id,
    name: e.name,
    equipment,
    kind,
    barWeightKg: equipment === 'barbell' ? 20 : null,
    defaultRestSec: kind === 'compound' ? 180 : 90,
    description: e.instructions.join(' '),
    muscles,
  });
}

const ALLOWED_EQUIP = new Set(['barbell', 'dumbbell', 'machine', 'cable', 'bodyweight', 'other']);
const ALLOWED_MUSCLE = new Set(Object.values(MUSCLE));
for (const r of rows) {
  if (!ALLOWED_EQUIP.has(r.equipment)) throw new Error(`bad equipment ${r.equipment} on ${r.id}`);
  if (r.kind !== 'compound' && r.kind !== 'isolation') throw new Error(`bad kind on ${r.id}`);
  for (const m of r.muscles) {
    if (!ALLOWED_MUSCLE.has(m.muscle)) throw new Error(`bad muscle ${m.muscle} on ${r.id}`);
    if (m.role !== 'prime' && m.role !== 'assist') throw new Error(`bad role on ${r.id}`);
  }
}

const chunk = (arr, n) =>
  Array.from({ length: Math.ceil(arr.length / n) }, (_, i) => arr.slice(i * n, i * n + n));

let sql = `-- The built-in exercise library.
--
-- Generated by scripts/build-seed.mjs from free-exercise-db (Unlicense, public
-- domain): https://github.com/yuhonas/free-exercise-db
-- Text only; the source's photographs are deliberately unused.
--
-- INSERT OR IGNORE so a re-run is harmless. Do not hand-edit: run \`npm run seed:gen\`.
--
-- The header sits INSIDE the first statement's chunk on purpose. Drizzle splits
-- this file on its breakpoint marker, and a chunk holding only comments prepares
-- to a NULL sqlite3_stmt; expo-sqlite then calls clear_bindings on it and the app
-- dies with a SIGSEGV rather than a SQL error. So: never lead with a marker, and
-- never write one inside a comment either -- the split does not know it is prose.
`;

/** Statements are joined by the marker, never prefixed with it. */
const statements = [];

for (const group of chunk(rows, 40)) {
  statements.push('INSERT OR IGNORE INTO `exercises` ' +
    '(`id`,`name`,`equipment`,`kind`,`is_custom`,`is_favorite`,`bar_weight_kg`,' +
    '`default_rest_sec`,`track_rpe`,`description`,`created_at`,`updated_at`) VALUES\n' +
    group.map((r) =>
      `(${q(r.id)},${q(r.name)},${q(r.equipment)},${q(r.kind)},0,0,` +
      `${r.barWeightKg ?? 'NULL'},${r.defaultRestSec},0,${q(r.description)},${STAMP},${STAMP})`,
    ).join(',\n') + ';');
}

const links = rows.flatMap((r) => r.muscles.map((m) => ({ id: r.id, ...m })));
for (const group of chunk(links, 120)) {
  statements.push('INSERT OR IGNORE INTO `exercise_muscles` ' +
    '(`exercise_id`,`muscle`,`role`) VALUES\n' +
    group.map((l) => `(${q(l.id)},${q(l.muscle)},${q(l.role)})`).join(',\n') + ';');
}

sql += statements.join('\n--> statement-breakpoint\n') + '\n';

writeFileSync(join(root, 'drizzle', '0001_seed_exercises.sql'), sql);

const hist = {};
for (const r of rows) hist[r.equipment] = (hist[r.equipment] ?? 0) + 1;
console.log(`exercises  ${rows.length}`);
console.log(`muscle rows ${links.length}`);
console.log('equipment  ', hist);
console.log('kind       ', rows.reduce((a, r) => ((a[r.kind] = (a[r.kind] ?? 0) + 1), a), {}));
console.log('dropped    ', dropped);
console.log('unmapped muscles', Object.fromEntries(droppedMuscles));
