// Generated by scripts/build-seed.mjs. Do not edit — run `pnpm seed:gen`.
//
// Metro resolves `require` statically, so an asset path assembled at runtime
// resolves to nothing at all. This map is what makes a per-row illustration
// possible; a built-in exercise has one, a custom exercise does not.
//
// Artwork (c) Bryl Lim, licensed CC BY-SA 4.0, from the @bryllim/workout-guide
// package — required straight out of node_modules rather than vendored, because
// 906 PNGs is 42 MB and git keeps binaries forever. The files are used
// unmodified, so they are not Adapted Material and ShareAlike never reaches this
// app's own source: tint at render time, never resize or re-encode. The credit
// is shown in the app on the exercise screen.

/** The three poses of one movement, in order. */
export type ExerciseFrames = readonly [number, number, number];

const ART: Record<string, ExerciseFrames> = {
  'bench-press': [
    require('@bryllim/workout-guide/assets/bench-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/bench-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/bench-press/frame-3.png'),
  ],
  'incline-bench-press': [
    require('@bryllim/workout-guide/assets/incline-bench-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/incline-bench-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/incline-bench-press/frame-3.png'),
  ],
  'incline-dumbbell-press': [
    require('@bryllim/workout-guide/assets/incline-dumbbell-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/incline-dumbbell-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/incline-dumbbell-press/frame-3.png'),
  ],
  'dumbbell-bench-press': [
    require('@bryllim/workout-guide/assets/dumbbell-bench-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-bench-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-bench-press/frame-3.png'),
  ],
  'decline-bench-press': [
    require('@bryllim/workout-guide/assets/decline-bench-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/decline-bench-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/decline-bench-press/frame-3.png'),
  ],
  'machine-chest-press': [
    require('@bryllim/workout-guide/assets/machine-chest-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/machine-chest-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/machine-chest-press/frame-3.png'),
  ],
  'pec-deck': [
    require('@bryllim/workout-guide/assets/pec-deck/frame-1.png'),
    require('@bryllim/workout-guide/assets/pec-deck/frame-2.png'),
    require('@bryllim/workout-guide/assets/pec-deck/frame-3.png'),
  ],
  'cable-fly': [
    require('@bryllim/workout-guide/assets/cable-fly/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-fly/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-fly/frame-3.png'),
  ],
  'push-up': [
    require('@bryllim/workout-guide/assets/push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/push-up/frame-3.png'),
  ],
  'weighted-push-up': [
    require('@bryllim/workout-guide/assets/weighted-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/weighted-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/weighted-push-up/frame-3.png'),
  ],
  'overhead-press': [
    require('@bryllim/workout-guide/assets/overhead-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/overhead-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/overhead-press/frame-3.png'),
  ],
  'seated-dumbbell-press': [
    require('@bryllim/workout-guide/assets/seated-dumbbell-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/seated-dumbbell-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/seated-dumbbell-press/frame-3.png'),
  ],
  'arnold-press': [
    require('@bryllim/workout-guide/assets/arnold-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/arnold-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/arnold-press/frame-3.png'),
  ],
  'lateral-raise': [
    require('@bryllim/workout-guide/assets/lateral-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/lateral-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/lateral-raise/frame-3.png'),
  ],
  'cable-lateral-raise': [
    require('@bryllim/workout-guide/assets/cable-lateral-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-lateral-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-lateral-raise/frame-3.png'),
  ],
  'front-raise': [
    require('@bryllim/workout-guide/assets/front-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/front-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/front-raise/frame-3.png'),
  ],
  'rear-delt-fly': [
    require('@bryllim/workout-guide/assets/rear-delt-fly/frame-1.png'),
    require('@bryllim/workout-guide/assets/rear-delt-fly/frame-2.png'),
    require('@bryllim/workout-guide/assets/rear-delt-fly/frame-3.png'),
  ],
  'reverse-pec-deck': [
    require('@bryllim/workout-guide/assets/reverse-pec-deck/frame-1.png'),
    require('@bryllim/workout-guide/assets/reverse-pec-deck/frame-2.png'),
    require('@bryllim/workout-guide/assets/reverse-pec-deck/frame-3.png'),
  ],
  'face-pull': [
    require('@bryllim/workout-guide/assets/face-pull/frame-1.png'),
    require('@bryllim/workout-guide/assets/face-pull/frame-2.png'),
    require('@bryllim/workout-guide/assets/face-pull/frame-3.png'),
  ],
  'upright-row': [
    require('@bryllim/workout-guide/assets/upright-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/upright-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/upright-row/frame-3.png'),
  ],
  deadlift: [
    require('@bryllim/workout-guide/assets/deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/deadlift/frame-3.png'),
  ],
  'romanian-deadlift': [
    require('@bryllim/workout-guide/assets/romanian-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/romanian-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/romanian-deadlift/frame-3.png'),
  ],
  'barbell-row': [
    require('@bryllim/workout-guide/assets/barbell-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/barbell-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/barbell-row/frame-3.png'),
  ],
  't-bar-row': [
    require('@bryllim/workout-guide/assets/t-bar-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/t-bar-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/t-bar-row/frame-3.png'),
  ],
  'dumbbell-bent-over-row': [
    require('@bryllim/workout-guide/assets/dumbbell-bent-over-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-bent-over-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-bent-over-row/frame-3.png'),
  ],
  'one-arm-dumbbell-row': [
    require('@bryllim/workout-guide/assets/one-arm-dumbbell-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/one-arm-dumbbell-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/one-arm-dumbbell-row/frame-3.png'),
  ],
  'chest-supported-row': [
    require('@bryllim/workout-guide/assets/chest-supported-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/chest-supported-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/chest-supported-row/frame-3.png'),
  ],
  'seated-row': [
    require('@bryllim/workout-guide/assets/seated-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/seated-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/seated-row/frame-3.png'),
  ],
  'machine-row': [
    require('@bryllim/workout-guide/assets/machine-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/machine-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/machine-row/frame-3.png'),
  ],
  'lat-pulldown': [
    require('@bryllim/workout-guide/assets/lat-pulldown/frame-1.png'),
    require('@bryllim/workout-guide/assets/lat-pulldown/frame-2.png'),
    require('@bryllim/workout-guide/assets/lat-pulldown/frame-3.png'),
  ],
  'close-grip-lat-pulldown': [
    require('@bryllim/workout-guide/assets/close-grip-lat-pulldown/frame-1.png'),
    require('@bryllim/workout-guide/assets/close-grip-lat-pulldown/frame-2.png'),
    require('@bryllim/workout-guide/assets/close-grip-lat-pulldown/frame-3.png'),
  ],
  'straight-arm-pulldown': [
    require('@bryllim/workout-guide/assets/straight-arm-pulldown/frame-1.png'),
    require('@bryllim/workout-guide/assets/straight-arm-pulldown/frame-2.png'),
    require('@bryllim/workout-guide/assets/straight-arm-pulldown/frame-3.png'),
  ],
  'pull-up': [
    require('@bryllim/workout-guide/assets/pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/pull-up/frame-3.png'),
  ],
  'assisted-pull-up': [
    require('@bryllim/workout-guide/assets/assisted-pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/assisted-pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/assisted-pull-up/frame-3.png'),
  ],
  'weighted-pull-up': [
    require('@bryllim/workout-guide/assets/weighted-pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/weighted-pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/weighted-pull-up/frame-3.png'),
  ],
  'chin-up': [
    require('@bryllim/workout-guide/assets/chin-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/chin-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/chin-up/frame-3.png'),
  ],
  shrug: [
    require('@bryllim/workout-guide/assets/shrug/frame-1.png'),
    require('@bryllim/workout-guide/assets/shrug/frame-2.png'),
    require('@bryllim/workout-guide/assets/shrug/frame-3.png'),
  ],
  squat: [
    require('@bryllim/workout-guide/assets/squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/squat/frame-3.png'),
  ],
  'front-squat': [
    require('@bryllim/workout-guide/assets/front-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/front-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/front-squat/frame-3.png'),
  ],
  'hack-squat': [
    require('@bryllim/workout-guide/assets/hack-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/hack-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/hack-squat/frame-3.png'),
  ],
  'leg-press': [
    require('@bryllim/workout-guide/assets/leg-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/leg-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/leg-press/frame-3.png'),
  ],
  'bulgarian-split-squat': [
    require('@bryllim/workout-guide/assets/bulgarian-split-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/bulgarian-split-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/bulgarian-split-squat/frame-3.png'),
  ],
  'walking-lunge': [
    require('@bryllim/workout-guide/assets/walking-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/walking-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/walking-lunge/frame-3.png'),
  ],
  'step-up': [
    require('@bryllim/workout-guide/assets/step-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/step-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/step-up/frame-3.png'),
  ],
  'leg-extension': [
    require('@bryllim/workout-guide/assets/leg-extension/frame-1.png'),
    require('@bryllim/workout-guide/assets/leg-extension/frame-2.png'),
    require('@bryllim/workout-guide/assets/leg-extension/frame-3.png'),
  ],
  'leg-curl': [
    require('@bryllim/workout-guide/assets/leg-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/leg-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/leg-curl/frame-3.png'),
  ],
  'seated-leg-curl': [
    require('@bryllim/workout-guide/assets/seated-leg-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/seated-leg-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/seated-leg-curl/frame-3.png'),
  ],
  'hip-thrust': [
    require('@bryllim/workout-guide/assets/hip-thrust/frame-1.png'),
    require('@bryllim/workout-guide/assets/hip-thrust/frame-2.png'),
    require('@bryllim/workout-guide/assets/hip-thrust/frame-3.png'),
  ],
  'glute-bridge': [
    require('@bryllim/workout-guide/assets/glute-bridge/frame-1.png'),
    require('@bryllim/workout-guide/assets/glute-bridge/frame-2.png'),
    require('@bryllim/workout-guide/assets/glute-bridge/frame-3.png'),
  ],
  'good-morning': [
    require('@bryllim/workout-guide/assets/good-morning/frame-1.png'),
    require('@bryllim/workout-guide/assets/good-morning/frame-2.png'),
    require('@bryllim/workout-guide/assets/good-morning/frame-3.png'),
  ],
  'standing-calf-raise': [
    require('@bryllim/workout-guide/assets/standing-calf-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/standing-calf-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/standing-calf-raise/frame-3.png'),
  ],
  'seated-calf-raise': [
    require('@bryllim/workout-guide/assets/seated-calf-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/seated-calf-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/seated-calf-raise/frame-3.png'),
  ],
  'bicep-curl': [
    require('@bryllim/workout-guide/assets/bicep-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/bicep-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/bicep-curl/frame-3.png'),
  ],
  'hammer-curl': [
    require('@bryllim/workout-guide/assets/hammer-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/hammer-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/hammer-curl/frame-3.png'),
  ],
  'preacher-curl': [
    require('@bryllim/workout-guide/assets/preacher-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/preacher-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/preacher-curl/frame-3.png'),
  ],
  'cable-curl': [
    require('@bryllim/workout-guide/assets/cable-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-curl/frame-3.png'),
  ],
  'reverse-curl': [
    require('@bryllim/workout-guide/assets/reverse-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/reverse-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/reverse-curl/frame-3.png'),
  ],
  'wrist-curl': [
    require('@bryllim/workout-guide/assets/wrist-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/wrist-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/wrist-curl/frame-3.png'),
  ],
  'tricep-pushdown': [
    require('@bryllim/workout-guide/assets/tricep-pushdown/frame-1.png'),
    require('@bryllim/workout-guide/assets/tricep-pushdown/frame-2.png'),
    require('@bryllim/workout-guide/assets/tricep-pushdown/frame-3.png'),
  ],
  'overhead-tricep-extension': [
    require('@bryllim/workout-guide/assets/overhead-tricep-extension/frame-1.png'),
    require('@bryllim/workout-guide/assets/overhead-tricep-extension/frame-2.png'),
    require('@bryllim/workout-guide/assets/overhead-tricep-extension/frame-3.png'),
  ],
  'skull-crusher': [
    require('@bryllim/workout-guide/assets/skull-crusher/frame-1.png'),
    require('@bryllim/workout-guide/assets/skull-crusher/frame-2.png'),
    require('@bryllim/workout-guide/assets/skull-crusher/frame-3.png'),
  ],
  'close-grip-bench-press': [
    require('@bryllim/workout-guide/assets/close-grip-bench-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/close-grip-bench-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/close-grip-bench-press/frame-3.png'),
  ],
  dip: [
    require('@bryllim/workout-guide/assets/dip/frame-1.png'),
    require('@bryllim/workout-guide/assets/dip/frame-2.png'),
    require('@bryllim/workout-guide/assets/dip/frame-3.png'),
  ],
  'assisted-dip': [
    require('@bryllim/workout-guide/assets/assisted-dip/frame-1.png'),
    require('@bryllim/workout-guide/assets/assisted-dip/frame-2.png'),
    require('@bryllim/workout-guide/assets/assisted-dip/frame-3.png'),
  ],
  plank: [
    require('@bryllim/workout-guide/assets/plank/frame-1.png'),
    require('@bryllim/workout-guide/assets/plank/frame-2.png'),
    require('@bryllim/workout-guide/assets/plank/frame-3.png'),
  ],
  'side-plank': [
    require('@bryllim/workout-guide/assets/side-plank/frame-1.png'),
    require('@bryllim/workout-guide/assets/side-plank/frame-2.png'),
    require('@bryllim/workout-guide/assets/side-plank/frame-3.png'),
  ],
  'hanging-leg-raise': [
    require('@bryllim/workout-guide/assets/hanging-leg-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/hanging-leg-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/hanging-leg-raise/frame-3.png'),
  ],
  'cable-crunch': [
    require('@bryllim/workout-guide/assets/cable-crunch/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-crunch/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-crunch/frame-3.png'),
  ],
  'ab-wheel': [
    require('@bryllim/workout-guide/assets/ab-wheel/frame-1.png'),
    require('@bryllim/workout-guide/assets/ab-wheel/frame-2.png'),
    require('@bryllim/workout-guide/assets/ab-wheel/frame-3.png'),
  ],
  running: [
    require('@bryllim/workout-guide/assets/running/frame-1.png'),
    require('@bryllim/workout-guide/assets/running/frame-2.png'),
    require('@bryllim/workout-guide/assets/running/frame-3.png'),
  ],
  walking: [
    require('@bryllim/workout-guide/assets/walking/frame-1.png'),
    require('@bryllim/workout-guide/assets/walking/frame-2.png'),
    require('@bryllim/workout-guide/assets/walking/frame-3.png'),
  ],
  cycling: [
    require('@bryllim/workout-guide/assets/cycling/frame-1.png'),
    require('@bryllim/workout-guide/assets/cycling/frame-2.png'),
    require('@bryllim/workout-guide/assets/cycling/frame-3.png'),
  ],
  rowing: [
    require('@bryllim/workout-guide/assets/rowing/frame-1.png'),
    require('@bryllim/workout-guide/assets/rowing/frame-2.png'),
    require('@bryllim/workout-guide/assets/rowing/frame-3.png'),
  ],
  'stair-climber': [
    require('@bryllim/workout-guide/assets/stair-climber/frame-1.png'),
    require('@bryllim/workout-guide/assets/stair-climber/frame-2.png'),
    require('@bryllim/workout-guide/assets/stair-climber/frame-3.png'),
  ],
  'dumbbell-fly': [
    require('@bryllim/workout-guide/assets/dumbbell-fly/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-fly/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-fly/frame-3.png'),
  ],
  'incline-cable-fly': [
    require('@bryllim/workout-guide/assets/incline-cable-fly/frame-1.png'),
    require('@bryllim/workout-guide/assets/incline-cable-fly/frame-2.png'),
    require('@bryllim/workout-guide/assets/incline-cable-fly/frame-3.png'),
  ],
  'decline-dumbbell-press': [
    require('@bryllim/workout-guide/assets/decline-dumbbell-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/decline-dumbbell-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/decline-dumbbell-press/frame-3.png'),
  ],
  'smith-machine-bench-press': [
    require('@bryllim/workout-guide/assets/smith-machine-bench-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/smith-machine-bench-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/smith-machine-bench-press/frame-3.png'),
  ],
  'landmine-press': [
    require('@bryllim/workout-guide/assets/landmine-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/landmine-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/landmine-press/frame-3.png'),
  ],
  'chest-dip': [
    require('@bryllim/workout-guide/assets/chest-dip/frame-1.png'),
    require('@bryllim/workout-guide/assets/chest-dip/frame-2.png'),
    require('@bryllim/workout-guide/assets/chest-dip/frame-3.png'),
  ],
  'weighted-dip': [
    require('@bryllim/workout-guide/assets/weighted-dip/frame-1.png'),
    require('@bryllim/workout-guide/assets/weighted-dip/frame-2.png'),
    require('@bryllim/workout-guide/assets/weighted-dip/frame-3.png'),
  ],
  'machine-shoulder-press': [
    require('@bryllim/workout-guide/assets/machine-shoulder-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/machine-shoulder-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/machine-shoulder-press/frame-3.png'),
  ],
  'standing-dumbbell-press': [
    require('@bryllim/workout-guide/assets/standing-dumbbell-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/standing-dumbbell-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/standing-dumbbell-press/frame-3.png'),
  ],
  'push-press': [
    require('@bryllim/workout-guide/assets/push-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/push-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/push-press/frame-3.png'),
  ],
  'machine-lateral-raise': [
    require('@bryllim/workout-guide/assets/machine-lateral-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/machine-lateral-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/machine-lateral-raise/frame-3.png'),
  ],
  'cable-front-raise': [
    require('@bryllim/workout-guide/assets/cable-front-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-front-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-front-raise/frame-3.png'),
  ],
  'plate-front-raise': [
    require('@bryllim/workout-guide/assets/plate-front-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/plate-front-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/plate-front-raise/frame-3.png'),
  ],
  'bent-over-rear-delt-raise': [
    require('@bryllim/workout-guide/assets/bent-over-rear-delt-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/bent-over-rear-delt-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/bent-over-rear-delt-raise/frame-3.png'),
  ],
  'cable-rear-delt-fly': [
    require('@bryllim/workout-guide/assets/cable-rear-delt-fly/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-rear-delt-fly/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-rear-delt-fly/frame-3.png'),
  ],
  'pendlay-row': [
    require('@bryllim/workout-guide/assets/pendlay-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/pendlay-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/pendlay-row/frame-3.png'),
  ],
  'inverted-row': [
    require('@bryllim/workout-guide/assets/inverted-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/inverted-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/inverted-row/frame-3.png'),
  ],
  'meadows-row': [
    require('@bryllim/workout-guide/assets/meadows-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/meadows-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/meadows-row/frame-3.png'),
  ],
  'single-arm-cable-row': [
    require('@bryllim/workout-guide/assets/single-arm-cable-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/single-arm-cable-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/single-arm-cable-row/frame-3.png'),
  ],
  'wide-grip-lat-pulldown': [
    require('@bryllim/workout-guide/assets/wide-grip-lat-pulldown/frame-1.png'),
    require('@bryllim/workout-guide/assets/wide-grip-lat-pulldown/frame-2.png'),
    require('@bryllim/workout-guide/assets/wide-grip-lat-pulldown/frame-3.png'),
  ],
  'neutral-grip-pull-up': [
    require('@bryllim/workout-guide/assets/neutral-grip-pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/neutral-grip-pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/neutral-grip-pull-up/frame-3.png'),
  ],
  'assisted-chin-up': [
    require('@bryllim/workout-guide/assets/assisted-chin-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/assisted-chin-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/assisted-chin-up/frame-3.png'),
  ],
  'weighted-chin-up': [
    require('@bryllim/workout-guide/assets/weighted-chin-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/weighted-chin-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/weighted-chin-up/frame-3.png'),
  ],
  'rack-pull': [
    require('@bryllim/workout-guide/assets/rack-pull/frame-1.png'),
    require('@bryllim/workout-guide/assets/rack-pull/frame-2.png'),
    require('@bryllim/workout-guide/assets/rack-pull/frame-3.png'),
  ],
  'back-extension': [
    require('@bryllim/workout-guide/assets/back-extension/frame-1.png'),
    require('@bryllim/workout-guide/assets/back-extension/frame-2.png'),
    require('@bryllim/workout-guide/assets/back-extension/frame-3.png'),
  ],
  'dumbbell-shrug': [
    require('@bryllim/workout-guide/assets/dumbbell-shrug/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-shrug/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-shrug/frame-3.png'),
  ],
  'goblet-squat': [
    require('@bryllim/workout-guide/assets/goblet-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/goblet-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/goblet-squat/frame-3.png'),
  ],
  'smith-machine-squat': [
    require('@bryllim/workout-guide/assets/smith-machine-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/smith-machine-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/smith-machine-squat/frame-3.png'),
  ],
  'belt-squat': [
    require('@bryllim/workout-guide/assets/belt-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/belt-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/belt-squat/frame-3.png'),
  ],
  'sumo-deadlift': [
    require('@bryllim/workout-guide/assets/sumo-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/sumo-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/sumo-deadlift/frame-3.png'),
  ],
  'trap-bar-deadlift': [
    require('@bryllim/workout-guide/assets/trap-bar-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/trap-bar-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/trap-bar-deadlift/frame-3.png'),
  ],
  'lying-leg-curl': [
    require('@bryllim/workout-guide/assets/lying-leg-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/lying-leg-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/lying-leg-curl/frame-3.png'),
  ],
  'nordic-hamstring-curl': [
    require('@bryllim/workout-guide/assets/nordic-hamstring-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/nordic-hamstring-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/nordic-hamstring-curl/frame-3.png'),
  ],
  'single-leg-romanian-deadlift': [
    require('@bryllim/workout-guide/assets/single-leg-romanian-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/single-leg-romanian-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/single-leg-romanian-deadlift/frame-3.png'),
  ],
  'reverse-lunge': [
    require('@bryllim/workout-guide/assets/reverse-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/reverse-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/reverse-lunge/frame-3.png'),
  ],
  'split-squat': [
    require('@bryllim/workout-guide/assets/split-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/split-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/split-squat/frame-3.png'),
  ],
  'cable-kickback': [
    require('@bryllim/workout-guide/assets/cable-kickback/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-kickback/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-kickback/frame-3.png'),
  ],
  'hip-abduction-machine': [
    require('@bryllim/workout-guide/assets/hip-abduction-machine/frame-1.png'),
    require('@bryllim/workout-guide/assets/hip-abduction-machine/frame-2.png'),
    require('@bryllim/workout-guide/assets/hip-abduction-machine/frame-3.png'),
  ],
  'single-leg-glute-bridge': [
    require('@bryllim/workout-guide/assets/single-leg-glute-bridge/frame-1.png'),
    require('@bryllim/workout-guide/assets/single-leg-glute-bridge/frame-2.png'),
    require('@bryllim/workout-guide/assets/single-leg-glute-bridge/frame-3.png'),
  ],
  'barbell-glute-bridge': [
    require('@bryllim/workout-guide/assets/barbell-glute-bridge/frame-1.png'),
    require('@bryllim/workout-guide/assets/barbell-glute-bridge/frame-2.png'),
    require('@bryllim/workout-guide/assets/barbell-glute-bridge/frame-3.png'),
  ],
  'dumbbell-glute-bridge': [
    require('@bryllim/workout-guide/assets/dumbbell-glute-bridge/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-glute-bridge/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-glute-bridge/frame-3.png'),
  ],
  'dumbbell-hip-thrust': [
    require('@bryllim/workout-guide/assets/dumbbell-hip-thrust/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-hip-thrust/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-hip-thrust/frame-3.png'),
  ],
  'smith-machine-hip-thrust': [
    require('@bryllim/workout-guide/assets/smith-machine-hip-thrust/frame-1.png'),
    require('@bryllim/workout-guide/assets/smith-machine-hip-thrust/frame-2.png'),
    require('@bryllim/workout-guide/assets/smith-machine-hip-thrust/frame-3.png'),
  ],
  'smith-machine-romanian-deadlift': [
    require('@bryllim/workout-guide/assets/smith-machine-romanian-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/smith-machine-romanian-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/smith-machine-romanian-deadlift/frame-3.png'),
  ],
  'dumbbell-romanian-deadlift': [
    require('@bryllim/workout-guide/assets/dumbbell-romanian-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-romanian-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-romanian-deadlift/frame-3.png'),
  ],
  'kettlebell-romanian-deadlift': [
    require('@bryllim/workout-guide/assets/kettlebell-romanian-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/kettlebell-romanian-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/kettlebell-romanian-deadlift/frame-3.png'),
  ],
  'cable-pull-through': [
    require('@bryllim/workout-guide/assets/cable-pull-through/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-pull-through/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-pull-through/frame-3.png'),
  ],
  'machine-glute-kickback': [
    require('@bryllim/workout-guide/assets/machine-glute-kickback/frame-1.png'),
    require('@bryllim/workout-guide/assets/machine-glute-kickback/frame-2.png'),
    require('@bryllim/workout-guide/assets/machine-glute-kickback/frame-3.png'),
  ],
  'cable-standing-hip-abduction': [
    require('@bryllim/workout-guide/assets/cable-standing-hip-abduction/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-standing-hip-abduction/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-standing-hip-abduction/frame-3.png'),
  ],
  'cable-standing-hip-adduction': [
    require('@bryllim/workout-guide/assets/cable-standing-hip-adduction/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-standing-hip-adduction/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-standing-hip-adduction/frame-3.png'),
  ],
  'hip-adduction-machine': [
    require('@bryllim/workout-guide/assets/hip-adduction-machine/frame-1.png'),
    require('@bryllim/workout-guide/assets/hip-adduction-machine/frame-2.png'),
    require('@bryllim/workout-guide/assets/hip-adduction-machine/frame-3.png'),
  ],
  'smith-machine-bulgarian-split-squat': [
    require('@bryllim/workout-guide/assets/smith-machine-bulgarian-split-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/smith-machine-bulgarian-split-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/smith-machine-bulgarian-split-squat/frame-3.png'),
  ],
  'smith-machine-reverse-lunge': [
    require('@bryllim/workout-guide/assets/smith-machine-reverse-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/smith-machine-reverse-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/smith-machine-reverse-lunge/frame-3.png'),
  ],
  'smith-machine-split-squat': [
    require('@bryllim/workout-guide/assets/smith-machine-split-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/smith-machine-split-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/smith-machine-split-squat/frame-3.png'),
  ],
  'heel-elevated-goblet-squat': [
    require('@bryllim/workout-guide/assets/heel-elevated-goblet-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/heel-elevated-goblet-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/heel-elevated-goblet-squat/frame-3.png'),
  ],
  'dumbbell-sumo-squat': [
    require('@bryllim/workout-guide/assets/dumbbell-sumo-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-sumo-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-sumo-squat/frame-3.png'),
  ],
  'dumbbell-sumo-deadlift': [
    require('@bryllim/workout-guide/assets/dumbbell-sumo-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-sumo-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-sumo-deadlift/frame-3.png'),
  ],
  'front-foot-elevated-split-squat': [
    require('@bryllim/workout-guide/assets/front-foot-elevated-split-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/front-foot-elevated-split-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/front-foot-elevated-split-squat/frame-3.png'),
  ],
  'deficit-reverse-lunge': [
    require('@bryllim/workout-guide/assets/deficit-reverse-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/deficit-reverse-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/deficit-reverse-lunge/frame-3.png'),
  ],
  'dumbbell-lateral-lunge': [
    require('@bryllim/workout-guide/assets/dumbbell-lateral-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-lateral-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-lateral-lunge/frame-3.png'),
  ],
  'dumbbell-curtsy-lunge': [
    require('@bryllim/workout-guide/assets/dumbbell-curtsy-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-curtsy-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-curtsy-lunge/frame-3.png'),
  ],
  'landmine-squat': [
    require('@bryllim/workout-guide/assets/landmine-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/landmine-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/landmine-squat/frame-3.png'),
  ],
  'landmine-romanian-deadlift': [
    require('@bryllim/workout-guide/assets/landmine-romanian-deadlift/frame-1.png'),
    require('@bryllim/workout-guide/assets/landmine-romanian-deadlift/frame-2.png'),
    require('@bryllim/workout-guide/assets/landmine-romanian-deadlift/frame-3.png'),
  ],
  'kettlebell-swing': [
    require('@bryllim/workout-guide/assets/kettlebell-swing/frame-1.png'),
    require('@bryllim/workout-guide/assets/kettlebell-swing/frame-2.png'),
    require('@bryllim/workout-guide/assets/kettlebell-swing/frame-3.png'),
  ],
  'glute-focused-back-extension': [
    require('@bryllim/workout-guide/assets/glute-focused-back-extension/frame-1.png'),
    require('@bryllim/workout-guide/assets/glute-focused-back-extension/frame-2.png'),
    require('@bryllim/workout-guide/assets/glute-focused-back-extension/frame-3.png'),
  ],
  'reverse-hyperextension': [
    require('@bryllim/workout-guide/assets/reverse-hyperextension/frame-1.png'),
    require('@bryllim/workout-guide/assets/reverse-hyperextension/frame-2.png'),
    require('@bryllim/workout-guide/assets/reverse-hyperextension/frame-3.png'),
  ],
  'donkey-calf-raise': [
    require('@bryllim/workout-guide/assets/donkey-calf-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/donkey-calf-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/donkey-calf-raise/frame-3.png'),
  ],
  'leg-press-calf-raise': [
    require('@bryllim/workout-guide/assets/leg-press-calf-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/leg-press-calf-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/leg-press-calf-raise/frame-3.png'),
  ],
  'wall-sit': [
    require('@bryllim/workout-guide/assets/wall-sit/frame-1.png'),
    require('@bryllim/workout-guide/assets/wall-sit/frame-2.png'),
    require('@bryllim/workout-guide/assets/wall-sit/frame-3.png'),
  ],
  'jump-squat': [
    require('@bryllim/workout-guide/assets/jump-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/jump-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/jump-squat/frame-3.png'),
  ],
  'incline-dumbbell-curl': [
    require('@bryllim/workout-guide/assets/incline-dumbbell-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/incline-dumbbell-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/incline-dumbbell-curl/frame-3.png'),
  ],
  'concentration-curl': [
    require('@bryllim/workout-guide/assets/concentration-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/concentration-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/concentration-curl/frame-3.png'),
  ],
  'ez-bar-curl': [
    require('@bryllim/workout-guide/assets/ez-bar-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/ez-bar-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/ez-bar-curl/frame-3.png'),
  ],
  'spider-curl': [
    require('@bryllim/workout-guide/assets/spider-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/spider-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/spider-curl/frame-3.png'),
  ],
  'rope-hammer-curl': [
    require('@bryllim/workout-guide/assets/rope-hammer-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/rope-hammer-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/rope-hammer-curl/frame-3.png'),
  ],
  'drag-curl': [
    require('@bryllim/workout-guide/assets/drag-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/drag-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/drag-curl/frame-3.png'),
  ],
  'rope-tricep-pushdown': [
    require('@bryllim/workout-guide/assets/rope-tricep-pushdown/frame-1.png'),
    require('@bryllim/workout-guide/assets/rope-tricep-pushdown/frame-2.png'),
    require('@bryllim/workout-guide/assets/rope-tricep-pushdown/frame-3.png'),
  ],
  'dumbbell-skull-crusher': [
    require('@bryllim/workout-guide/assets/dumbbell-skull-crusher/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-skull-crusher/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-skull-crusher/frame-3.png'),
  ],
  'single-dumbbell-skullcrusher': [
    require('@bryllim/workout-guide/assets/single-dumbbell-skullcrusher/frame-1.png'),
    require('@bryllim/workout-guide/assets/single-dumbbell-skullcrusher/frame-2.png'),
    require('@bryllim/workout-guide/assets/single-dumbbell-skullcrusher/frame-3.png'),
  ],
  'dumbbell-overhead-tricep-extension': [
    require('@bryllim/workout-guide/assets/dumbbell-overhead-tricep-extension/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-overhead-tricep-extension/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-overhead-tricep-extension/frame-3.png'),
  ],
  'single-arm-dumbbell-tricep-extension': [
    require('@bryllim/workout-guide/assets/single-arm-dumbbell-tricep-extension/frame-1.png'),
    require('@bryllim/workout-guide/assets/single-arm-dumbbell-tricep-extension/frame-2.png'),
    require('@bryllim/workout-guide/assets/single-arm-dumbbell-tricep-extension/frame-3.png'),
  ],
  'bench-dip': [
    require('@bryllim/workout-guide/assets/bench-dip/frame-1.png'),
    require('@bryllim/workout-guide/assets/bench-dip/frame-2.png'),
    require('@bryllim/workout-guide/assets/bench-dip/frame-3.png'),
  ],
  'tricep-kickback': [
    require('@bryllim/workout-guide/assets/tricep-kickback/frame-1.png'),
    require('@bryllim/workout-guide/assets/tricep-kickback/frame-2.png'),
    require('@bryllim/workout-guide/assets/tricep-kickback/frame-3.png'),
  ],
  'wrist-extension': [
    require('@bryllim/workout-guide/assets/wrist-extension/frame-1.png'),
    require('@bryllim/workout-guide/assets/wrist-extension/frame-2.png'),
    require('@bryllim/workout-guide/assets/wrist-extension/frame-3.png'),
  ],
  'farmer-carry': [
    require('@bryllim/workout-guide/assets/farmer-carry/frame-1.png'),
    require('@bryllim/workout-guide/assets/farmer-carry/frame-2.png'),
    require('@bryllim/workout-guide/assets/farmer-carry/frame-3.png'),
  ],
  crunch: [
    require('@bryllim/workout-guide/assets/crunch/frame-1.png'),
    require('@bryllim/workout-guide/assets/crunch/frame-2.png'),
    require('@bryllim/workout-guide/assets/crunch/frame-3.png'),
  ],
  'reverse-crunch': [
    require('@bryllim/workout-guide/assets/reverse-crunch/frame-1.png'),
    require('@bryllim/workout-guide/assets/reverse-crunch/frame-2.png'),
    require('@bryllim/workout-guide/assets/reverse-crunch/frame-3.png'),
  ],
  'russian-twist': [
    require('@bryllim/workout-guide/assets/russian-twist/frame-1.png'),
    require('@bryllim/workout-guide/assets/russian-twist/frame-2.png'),
    require('@bryllim/workout-guide/assets/russian-twist/frame-3.png'),
  ],
  'bicycle-crunch': [
    require('@bryllim/workout-guide/assets/bicycle-crunch/frame-1.png'),
    require('@bryllim/workout-guide/assets/bicycle-crunch/frame-2.png'),
    require('@bryllim/workout-guide/assets/bicycle-crunch/frame-3.png'),
  ],
  'mountain-climber': [
    require('@bryllim/workout-guide/assets/mountain-climber/frame-1.png'),
    require('@bryllim/workout-guide/assets/mountain-climber/frame-2.png'),
    require('@bryllim/workout-guide/assets/mountain-climber/frame-3.png'),
  ],
  'dead-bug': [
    require('@bryllim/workout-guide/assets/dead-bug/frame-1.png'),
    require('@bryllim/workout-guide/assets/dead-bug/frame-2.png'),
    require('@bryllim/workout-guide/assets/dead-bug/frame-3.png'),
  ],
  'bird-dog': [
    require('@bryllim/workout-guide/assets/bird-dog/frame-1.png'),
    require('@bryllim/workout-guide/assets/bird-dog/frame-2.png'),
    require('@bryllim/workout-guide/assets/bird-dog/frame-3.png'),
  ],
  'pallof-press': [
    require('@bryllim/workout-guide/assets/pallof-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/pallof-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/pallof-press/frame-3.png'),
  ],
  'cable-woodchop': [
    require('@bryllim/workout-guide/assets/cable-woodchop/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-woodchop/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-woodchop/frame-3.png'),
  ],
  'half-kneeling-pallof-press': [
    require('@bryllim/workout-guide/assets/half-kneeling-pallof-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/half-kneeling-pallof-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/half-kneeling-pallof-press/frame-3.png'),
  ],
  'cable-pallof-hold': [
    require('@bryllim/workout-guide/assets/cable-pallof-hold/frame-1.png'),
    require('@bryllim/workout-guide/assets/cable-pallof-hold/frame-2.png'),
    require('@bryllim/workout-guide/assets/cable-pallof-hold/frame-3.png'),
  ],
  'hanging-knee-raise': [
    require('@bryllim/workout-guide/assets/hanging-knee-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/hanging-knee-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/hanging-knee-raise/frame-3.png'),
  ],
  'captains-chair-knee-raise': [
    require('@bryllim/workout-guide/assets/captains-chair-knee-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/captains-chair-knee-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/captains-chair-knee-raise/frame-3.png'),
  ],
  'decline-sit-up': [
    require('@bryllim/workout-guide/assets/decline-sit-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/decline-sit-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/decline-sit-up/frame-3.png'),
  ],
  'weighted-crunch': [
    require('@bryllim/workout-guide/assets/weighted-crunch/frame-1.png'),
    require('@bryllim/workout-guide/assets/weighted-crunch/frame-2.png'),
    require('@bryllim/workout-guide/assets/weighted-crunch/frame-3.png'),
  ],
  'weighted-russian-twist': [
    require('@bryllim/workout-guide/assets/weighted-russian-twist/frame-1.png'),
    require('@bryllim/workout-guide/assets/weighted-russian-twist/frame-2.png'),
    require('@bryllim/workout-guide/assets/weighted-russian-twist/frame-3.png'),
  ],
  'dumbbell-side-bend': [
    require('@bryllim/workout-guide/assets/dumbbell-side-bend/frame-1.png'),
    require('@bryllim/workout-guide/assets/dumbbell-side-bend/frame-2.png'),
    require('@bryllim/workout-guide/assets/dumbbell-side-bend/frame-3.png'),
  ],
  elliptical: [
    require('@bryllim/workout-guide/assets/elliptical/frame-1.png'),
    require('@bryllim/workout-guide/assets/elliptical/frame-2.png'),
    require('@bryllim/workout-guide/assets/elliptical/frame-3.png'),
  ],
  swimming: [
    require('@bryllim/workout-guide/assets/swimming/frame-1.png'),
    require('@bryllim/workout-guide/assets/swimming/frame-2.png'),
    require('@bryllim/workout-guide/assets/swimming/frame-3.png'),
  ],
  'jump-rope': [
    require('@bryllim/workout-guide/assets/jump-rope/frame-1.png'),
    require('@bryllim/workout-guide/assets/jump-rope/frame-2.png'),
    require('@bryllim/workout-guide/assets/jump-rope/frame-3.png'),
  ],
  'assault-bike': [
    require('@bryllim/workout-guide/assets/assault-bike/frame-1.png'),
    require('@bryllim/workout-guide/assets/assault-bike/frame-2.png'),
    require('@bryllim/workout-guide/assets/assault-bike/frame-3.png'),
  ],
  skierg: [
    require('@bryllim/workout-guide/assets/skierg/frame-1.png'),
    require('@bryllim/workout-guide/assets/skierg/frame-2.png'),
    require('@bryllim/workout-guide/assets/skierg/frame-3.png'),
  ],
  hiking: [
    require('@bryllim/workout-guide/assets/hiking/frame-1.png'),
    require('@bryllim/workout-guide/assets/hiking/frame-2.png'),
    require('@bryllim/workout-guide/assets/hiking/frame-3.png'),
  ],
  'treadmill-incline-walk': [
    require('@bryllim/workout-guide/assets/treadmill-incline-walk/frame-1.png'),
    require('@bryllim/workout-guide/assets/treadmill-incline-walk/frame-2.png'),
    require('@bryllim/workout-guide/assets/treadmill-incline-walk/frame-3.png'),
  ],
  'battle-ropes': [
    require('@bryllim/workout-guide/assets/battle-ropes/frame-1.png'),
    require('@bryllim/workout-guide/assets/battle-ropes/frame-2.png'),
    require('@bryllim/workout-guide/assets/battle-ropes/frame-3.png'),
  ],
  'incline-push-up': [
    require('@bryllim/workout-guide/assets/incline-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/incline-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/incline-push-up/frame-3.png'),
  ],
  'knee-push-up': [
    require('@bryllim/workout-guide/assets/knee-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/knee-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/knee-push-up/frame-3.png'),
  ],
  'wide-push-up': [
    require('@bryllim/workout-guide/assets/wide-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/wide-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/wide-push-up/frame-3.png'),
  ],
  'diamond-push-up': [
    require('@bryllim/workout-guide/assets/diamond-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/diamond-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/diamond-push-up/frame-3.png'),
  ],
  'decline-push-up': [
    require('@bryllim/workout-guide/assets/decline-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/decline-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/decline-push-up/frame-3.png'),
  ],
  'pike-push-up': [
    require('@bryllim/workout-guide/assets/pike-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/pike-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/pike-push-up/frame-3.png'),
  ],
  'feet-elevated-pike-push-up': [
    require('@bryllim/workout-guide/assets/feet-elevated-pike-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/feet-elevated-pike-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/feet-elevated-pike-push-up/frame-3.png'),
  ],
  'archer-push-up': [
    require('@bryllim/workout-guide/assets/archer-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/archer-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/archer-push-up/frame-3.png'),
  ],
  'typewriter-push-up': [
    require('@bryllim/workout-guide/assets/typewriter-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/typewriter-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/typewriter-push-up/frame-3.png'),
  ],
  'explosive-push-up': [
    require('@bryllim/workout-guide/assets/explosive-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/explosive-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/explosive-push-up/frame-3.png'),
  ],
  'hindu-push-up': [
    require('@bryllim/workout-guide/assets/hindu-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/hindu-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/hindu-push-up/frame-3.png'),
  ],
  'scapular-push-up': [
    require('@bryllim/workout-guide/assets/scapular-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/scapular-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/scapular-push-up/frame-3.png'),
  ],
  'push-up-shoulder-tap': [
    require('@bryllim/workout-guide/assets/push-up-shoulder-tap/frame-1.png'),
    require('@bryllim/workout-guide/assets/push-up-shoulder-tap/frame-2.png'),
    require('@bryllim/workout-guide/assets/push-up-shoulder-tap/frame-3.png'),
  ],
  'wall-push-up': [
    require('@bryllim/workout-guide/assets/wall-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/wall-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/wall-push-up/frame-3.png'),
  ],
  'wall-walk': [
    require('@bryllim/workout-guide/assets/wall-walk/frame-1.png'),
    require('@bryllim/workout-guide/assets/wall-walk/frame-2.png'),
    require('@bryllim/workout-guide/assets/wall-walk/frame-3.png'),
  ],
  'wall-handstand-push-up': [
    require('@bryllim/workout-guide/assets/wall-handstand-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/wall-handstand-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/wall-handstand-push-up/frame-3.png'),
  ],
  'handstand-push-up': [
    require('@bryllim/workout-guide/assets/handstand-push-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/handstand-push-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/handstand-push-up/frame-3.png'),
  ],
  'chair-dip': [
    require('@bryllim/workout-guide/assets/chair-dip/frame-1.png'),
    require('@bryllim/workout-guide/assets/chair-dip/frame-2.png'),
    require('@bryllim/workout-guide/assets/chair-dip/frame-3.png'),
  ],
  'doorway-row': [
    require('@bryllim/workout-guide/assets/doorway-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/doorway-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/doorway-row/frame-3.png'),
  ],
  'towel-row': [
    require('@bryllim/workout-guide/assets/towel-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/towel-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/towel-row/frame-3.png'),
  ],
  'prone-y-raise': [
    require('@bryllim/workout-guide/assets/prone-y-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/prone-y-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/prone-y-raise/frame-3.png'),
  ],
  'prone-t-raise': [
    require('@bryllim/workout-guide/assets/prone-t-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/prone-t-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/prone-t-raise/frame-3.png'),
  ],
  superman: [
    require('@bryllim/workout-guide/assets/superman/frame-1.png'),
    require('@bryllim/workout-guide/assets/superman/frame-2.png'),
    require('@bryllim/workout-guide/assets/superman/frame-3.png'),
  ],
  'superman-hold': [
    require('@bryllim/workout-guide/assets/superman-hold/frame-1.png'),
    require('@bryllim/workout-guide/assets/superman-hold/frame-2.png'),
    require('@bryllim/workout-guide/assets/superman-hold/frame-3.png'),
  ],
  'reverse-snow-angel': [
    require('@bryllim/workout-guide/assets/reverse-snow-angel/frame-1.png'),
    require('@bryllim/workout-guide/assets/reverse-snow-angel/frame-2.png'),
    require('@bryllim/workout-guide/assets/reverse-snow-angel/frame-3.png'),
  ],
  'dead-hang': [
    require('@bryllim/workout-guide/assets/dead-hang/frame-1.png'),
    require('@bryllim/workout-guide/assets/dead-hang/frame-2.png'),
    require('@bryllim/workout-guide/assets/dead-hang/frame-3.png'),
  ],
  'active-hang': [
    require('@bryllim/workout-guide/assets/active-hang/frame-1.png'),
    require('@bryllim/workout-guide/assets/active-hang/frame-2.png'),
    require('@bryllim/workout-guide/assets/active-hang/frame-3.png'),
  ],
  'scapular-pull-up': [
    require('@bryllim/workout-guide/assets/scapular-pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/scapular-pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/scapular-pull-up/frame-3.png'),
  ],
  'negative-pull-up': [
    require('@bryllim/workout-guide/assets/negative-pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/negative-pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/negative-pull-up/frame-3.png'),
  ],
  'commando-pull-up': [
    require('@bryllim/workout-guide/assets/commando-pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/commando-pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/commando-pull-up/frame-3.png'),
  ],
  'l-sit-pull-up': [
    require('@bryllim/workout-guide/assets/l-sit-pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/l-sit-pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/l-sit-pull-up/frame-3.png'),
  ],
  'towel-pull-up': [
    require('@bryllim/workout-guide/assets/towel-pull-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/towel-pull-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/towel-pull-up/frame-3.png'),
  ],
  'bodyweight-squat': [
    require('@bryllim/workout-guide/assets/bodyweight-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/bodyweight-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/bodyweight-squat/frame-3.png'),
  ],
  'pistol-squat': [
    require('@bryllim/workout-guide/assets/pistol-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/pistol-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/pistol-squat/frame-3.png'),
  ],
  'assisted-pistol-squat': [
    require('@bryllim/workout-guide/assets/assisted-pistol-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/assisted-pistol-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/assisted-pistol-squat/frame-3.png'),
  ],
  'shrimp-squat': [
    require('@bryllim/workout-guide/assets/shrimp-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/shrimp-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/shrimp-squat/frame-3.png'),
  ],
  'cossack-squat': [
    require('@bryllim/workout-guide/assets/cossack-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/cossack-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/cossack-squat/frame-3.png'),
  ],
  'sissy-squat': [
    require('@bryllim/workout-guide/assets/sissy-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/sissy-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/sissy-squat/frame-3.png'),
  ],
  'forward-lunge': [
    require('@bryllim/workout-guide/assets/forward-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/forward-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/forward-lunge/frame-3.png'),
  ],
  'lateral-lunge': [
    require('@bryllim/workout-guide/assets/lateral-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/lateral-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/lateral-lunge/frame-3.png'),
  ],
  'curtsy-lunge': [
    require('@bryllim/workout-guide/assets/curtsy-lunge/frame-1.png'),
    require('@bryllim/workout-guide/assets/curtsy-lunge/frame-2.png'),
    require('@bryllim/workout-guide/assets/curtsy-lunge/frame-3.png'),
  ],
  'skater-squat': [
    require('@bryllim/workout-guide/assets/skater-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/skater-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/skater-squat/frame-3.png'),
  ],
  'single-leg-box-squat': [
    require('@bryllim/workout-guide/assets/single-leg-box-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/single-leg-box-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/single-leg-box-squat/frame-3.png'),
  ],
  'step-down': [
    require('@bryllim/workout-guide/assets/step-down/frame-1.png'),
    require('@bryllim/workout-guide/assets/step-down/frame-2.png'),
    require('@bryllim/workout-guide/assets/step-down/frame-3.png'),
  ],
  'calf-raise': [
    require('@bryllim/workout-guide/assets/calf-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/calf-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/calf-raise/frame-3.png'),
  ],
  'single-leg-calf-raise': [
    require('@bryllim/workout-guide/assets/single-leg-calf-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/single-leg-calf-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/single-leg-calf-raise/frame-3.png'),
  ],
  'glute-bridge-march': [
    require('@bryllim/workout-guide/assets/glute-bridge-march/frame-1.png'),
    require('@bryllim/workout-guide/assets/glute-bridge-march/frame-2.png'),
    require('@bryllim/workout-guide/assets/glute-bridge-march/frame-3.png'),
  ],
  'frog-pump': [
    require('@bryllim/workout-guide/assets/frog-pump/frame-1.png'),
    require('@bryllim/workout-guide/assets/frog-pump/frame-2.png'),
    require('@bryllim/workout-guide/assets/frog-pump/frame-3.png'),
  ],
  'donkey-kick': [
    require('@bryllim/workout-guide/assets/donkey-kick/frame-1.png'),
    require('@bryllim/workout-guide/assets/donkey-kick/frame-2.png'),
    require('@bryllim/workout-guide/assets/donkey-kick/frame-3.png'),
  ],
  'fire-hydrant': [
    require('@bryllim/workout-guide/assets/fire-hydrant/frame-1.png'),
    require('@bryllim/workout-guide/assets/fire-hydrant/frame-2.png'),
    require('@bryllim/workout-guide/assets/fire-hydrant/frame-3.png'),
  ],
  clamshell: [
    require('@bryllim/workout-guide/assets/clamshell/frame-1.png'),
    require('@bryllim/workout-guide/assets/clamshell/frame-2.png'),
    require('@bryllim/workout-guide/assets/clamshell/frame-3.png'),
  ],
  'hip-airplane': [
    require('@bryllim/workout-guide/assets/hip-airplane/frame-1.png'),
    require('@bryllim/workout-guide/assets/hip-airplane/frame-2.png'),
    require('@bryllim/workout-guide/assets/hip-airplane/frame-3.png'),
  ],
  'side-lying-hip-abduction': [
    require('@bryllim/workout-guide/assets/side-lying-hip-abduction/frame-1.png'),
    require('@bryllim/workout-guide/assets/side-lying-hip-abduction/frame-2.png'),
    require('@bryllim/workout-guide/assets/side-lying-hip-abduction/frame-3.png'),
  ],
  'side-lying-leg-raise': [
    require('@bryllim/workout-guide/assets/side-lying-leg-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/side-lying-leg-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/side-lying-leg-raise/frame-3.png'),
  ],
  'lying-hamstring-walkout': [
    require('@bryllim/workout-guide/assets/lying-hamstring-walkout/frame-1.png'),
    require('@bryllim/workout-guide/assets/lying-hamstring-walkout/frame-2.png'),
    require('@bryllim/workout-guide/assets/lying-hamstring-walkout/frame-3.png'),
  ],
  'towel-hamstring-curl': [
    require('@bryllim/workout-guide/assets/towel-hamstring-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/towel-hamstring-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/towel-hamstring-curl/frame-3.png'),
  ],
  'stability-ball-hamstring-curl': [
    require('@bryllim/workout-guide/assets/stability-ball-hamstring-curl/frame-1.png'),
    require('@bryllim/workout-guide/assets/stability-ball-hamstring-curl/frame-2.png'),
    require('@bryllim/workout-guide/assets/stability-ball-hamstring-curl/frame-3.png'),
  ],
  'banded-glute-bridge': [
    require('@bryllim/workout-guide/assets/banded-glute-bridge/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-glute-bridge/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-glute-bridge/frame-3.png'),
  ],
  'banded-hip-thrust': [
    require('@bryllim/workout-guide/assets/banded-hip-thrust/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-hip-thrust/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-hip-thrust/frame-3.png'),
  ],
  'banded-frog-pump': [
    require('@bryllim/workout-guide/assets/banded-frog-pump/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-frog-pump/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-frog-pump/frame-3.png'),
  ],
  'banded-clamshell': [
    require('@bryllim/workout-guide/assets/banded-clamshell/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-clamshell/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-clamshell/frame-3.png'),
  ],
  'banded-lateral-walk': [
    require('@bryllim/workout-guide/assets/banded-lateral-walk/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-lateral-walk/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-lateral-walk/frame-3.png'),
  ],
  'banded-monster-walk': [
    require('@bryllim/workout-guide/assets/banded-monster-walk/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-monster-walk/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-monster-walk/frame-3.png'),
  ],
  'banded-squat': [
    require('@bryllim/workout-guide/assets/banded-squat/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-squat/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-squat/frame-3.png'),
  ],
  'banded-donkey-kick': [
    require('@bryllim/workout-guide/assets/banded-donkey-kick/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-donkey-kick/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-donkey-kick/frame-3.png'),
  ],
  'banded-fire-hydrant': [
    require('@bryllim/workout-guide/assets/banded-fire-hydrant/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-fire-hydrant/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-fire-hydrant/frame-3.png'),
  ],
  'banded-kickback': [
    require('@bryllim/workout-guide/assets/banded-kickback/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-kickback/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-kickback/frame-3.png'),
  ],
  'banded-standing-hip-abduction': [
    require('@bryllim/workout-guide/assets/banded-standing-hip-abduction/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-standing-hip-abduction/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-standing-hip-abduction/frame-3.png'),
  ],
  'banded-seated-hip-abduction': [
    require('@bryllim/workout-guide/assets/banded-seated-hip-abduction/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-seated-hip-abduction/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-seated-hip-abduction/frame-3.png'),
  ],
  'band-pull-apart': [
    require('@bryllim/workout-guide/assets/band-pull-apart/frame-1.png'),
    require('@bryllim/workout-guide/assets/band-pull-apart/frame-2.png'),
    require('@bryllim/workout-guide/assets/band-pull-apart/frame-3.png'),
  ],
  'banded-face-pull': [
    require('@bryllim/workout-guide/assets/banded-face-pull/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-face-pull/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-face-pull/frame-3.png'),
  ],
  'banded-row': [
    require('@bryllim/workout-guide/assets/banded-row/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-row/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-row/frame-3.png'),
  ],
  'banded-lat-pulldown': [
    require('@bryllim/workout-guide/assets/banded-lat-pulldown/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-lat-pulldown/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-lat-pulldown/frame-3.png'),
  ],
  'banded-pallof-press': [
    require('@bryllim/workout-guide/assets/banded-pallof-press/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-pallof-press/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-pallof-press/frame-3.png'),
  ],
  'banded-woodchop': [
    require('@bryllim/workout-guide/assets/banded-woodchop/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-woodchop/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-woodchop/frame-3.png'),
  ],
  'banded-dead-bug': [
    require('@bryllim/workout-guide/assets/banded-dead-bug/frame-1.png'),
    require('@bryllim/workout-guide/assets/banded-dead-bug/frame-2.png'),
    require('@bryllim/workout-guide/assets/banded-dead-bug/frame-3.png'),
  ],
  'hollow-body-hold': [
    require('@bryllim/workout-guide/assets/hollow-body-hold/frame-1.png'),
    require('@bryllim/workout-guide/assets/hollow-body-hold/frame-2.png'),
    require('@bryllim/workout-guide/assets/hollow-body-hold/frame-3.png'),
  ],
  'hollow-rock': [
    require('@bryllim/workout-guide/assets/hollow-rock/frame-1.png'),
    require('@bryllim/workout-guide/assets/hollow-rock/frame-2.png'),
    require('@bryllim/workout-guide/assets/hollow-rock/frame-3.png'),
  ],
  'v-up': [
    require('@bryllim/workout-guide/assets/v-up/frame-1.png'),
    require('@bryllim/workout-guide/assets/v-up/frame-2.png'),
    require('@bryllim/workout-guide/assets/v-up/frame-3.png'),
  ],
  'flutter-kick': [
    require('@bryllim/workout-guide/assets/flutter-kick/frame-1.png'),
    require('@bryllim/workout-guide/assets/flutter-kick/frame-2.png'),
    require('@bryllim/workout-guide/assets/flutter-kick/frame-3.png'),
  ],
  'lying-leg-raise': [
    require('@bryllim/workout-guide/assets/lying-leg-raise/frame-1.png'),
    require('@bryllim/workout-guide/assets/lying-leg-raise/frame-2.png'),
    require('@bryllim/workout-guide/assets/lying-leg-raise/frame-3.png'),
  ],
  'toe-touch': [
    require('@bryllim/workout-guide/assets/toe-touch/frame-1.png'),
    require('@bryllim/workout-guide/assets/toe-touch/frame-2.png'),
    require('@bryllim/workout-guide/assets/toe-touch/frame-3.png'),
  ],
  'heel-tap': [
    require('@bryllim/workout-guide/assets/heel-tap/frame-1.png'),
    require('@bryllim/workout-guide/assets/heel-tap/frame-2.png'),
    require('@bryllim/workout-guide/assets/heel-tap/frame-3.png'),
  ],
  'plank-shoulder-tap': [
    require('@bryllim/workout-guide/assets/plank-shoulder-tap/frame-1.png'),
    require('@bryllim/workout-guide/assets/plank-shoulder-tap/frame-2.png'),
    require('@bryllim/workout-guide/assets/plank-shoulder-tap/frame-3.png'),
  ],
  'plank-jack': [
    require('@bryllim/workout-guide/assets/plank-jack/frame-1.png'),
    require('@bryllim/workout-guide/assets/plank-jack/frame-2.png'),
    require('@bryllim/workout-guide/assets/plank-jack/frame-3.png'),
  ],
  'bear-plank': [
    require('@bryllim/workout-guide/assets/bear-plank/frame-1.png'),
    require('@bryllim/workout-guide/assets/bear-plank/frame-2.png'),
    require('@bryllim/workout-guide/assets/bear-plank/frame-3.png'),
  ],
  'bear-crawl': [
    require('@bryllim/workout-guide/assets/bear-crawl/frame-1.png'),
    require('@bryllim/workout-guide/assets/bear-crawl/frame-2.png'),
    require('@bryllim/workout-guide/assets/bear-crawl/frame-3.png'),
  ],
  'crab-walk': [
    require('@bryllim/workout-guide/assets/crab-walk/frame-1.png'),
    require('@bryllim/workout-guide/assets/crab-walk/frame-2.png'),
    require('@bryllim/workout-guide/assets/crab-walk/frame-3.png'),
  ],
  inchworm: [
    require('@bryllim/workout-guide/assets/inchworm/frame-1.png'),
    require('@bryllim/workout-guide/assets/inchworm/frame-2.png'),
    require('@bryllim/workout-guide/assets/inchworm/frame-3.png'),
  ],
  'l-sit-hold': [
    require('@bryllim/workout-guide/assets/l-sit-hold/frame-1.png'),
    require('@bryllim/workout-guide/assets/l-sit-hold/frame-2.png'),
    require('@bryllim/workout-guide/assets/l-sit-hold/frame-3.png'),
  ],
  'seated-knee-tuck': [
    require('@bryllim/workout-guide/assets/seated-knee-tuck/frame-1.png'),
    require('@bryllim/workout-guide/assets/seated-knee-tuck/frame-2.png'),
    require('@bryllim/workout-guide/assets/seated-knee-tuck/frame-3.png'),
  ],
  'side-plank-hip-dip': [
    require('@bryllim/workout-guide/assets/side-plank-hip-dip/frame-1.png'),
    require('@bryllim/workout-guide/assets/side-plank-hip-dip/frame-2.png'),
    require('@bryllim/workout-guide/assets/side-plank-hip-dip/frame-3.png'),
  ],
  'copenhagen-plank': [
    require('@bryllim/workout-guide/assets/copenhagen-plank/frame-1.png'),
    require('@bryllim/workout-guide/assets/copenhagen-plank/frame-2.png'),
    require('@bryllim/workout-guide/assets/copenhagen-plank/frame-3.png'),
  ],
  'dragon-flag': [
    require('@bryllim/workout-guide/assets/dragon-flag/frame-1.png'),
    require('@bryllim/workout-guide/assets/dragon-flag/frame-2.png'),
    require('@bryllim/workout-guide/assets/dragon-flag/frame-3.png'),
  ],
  burpee: [
    require('@bryllim/workout-guide/assets/burpee/frame-1.png'),
    require('@bryllim/workout-guide/assets/burpee/frame-2.png'),
    require('@bryllim/workout-guide/assets/burpee/frame-3.png'),
  ],
  'half-burpee': [
    require('@bryllim/workout-guide/assets/half-burpee/frame-1.png'),
    require('@bryllim/workout-guide/assets/half-burpee/frame-2.png'),
    require('@bryllim/workout-guide/assets/half-burpee/frame-3.png'),
  ],
  'squat-thrust': [
    require('@bryllim/workout-guide/assets/squat-thrust/frame-1.png'),
    require('@bryllim/workout-guide/assets/squat-thrust/frame-2.png'),
    require('@bryllim/workout-guide/assets/squat-thrust/frame-3.png'),
  ],
  'high-knees': [
    require('@bryllim/workout-guide/assets/high-knees/frame-1.png'),
    require('@bryllim/workout-guide/assets/high-knees/frame-2.png'),
    require('@bryllim/workout-guide/assets/high-knees/frame-3.png'),
  ],
  'jumping-jack': [
    require('@bryllim/workout-guide/assets/jumping-jack/frame-1.png'),
    require('@bryllim/workout-guide/assets/jumping-jack/frame-2.png'),
    require('@bryllim/workout-guide/assets/jumping-jack/frame-3.png'),
  ],
  'skater-hop': [
    require('@bryllim/workout-guide/assets/skater-hop/frame-1.png'),
    require('@bryllim/workout-guide/assets/skater-hop/frame-2.png'),
    require('@bryllim/workout-guide/assets/skater-hop/frame-3.png'),
  ],
  'lateral-shuffle': [
    require('@bryllim/workout-guide/assets/lateral-shuffle/frame-1.png'),
    require('@bryllim/workout-guide/assets/lateral-shuffle/frame-2.png'),
    require('@bryllim/workout-guide/assets/lateral-shuffle/frame-3.png'),
  ],
  'fast-feet': [
    require('@bryllim/workout-guide/assets/fast-feet/frame-1.png'),
    require('@bryllim/workout-guide/assets/fast-feet/frame-2.png'),
    require('@bryllim/workout-guide/assets/fast-feet/frame-3.png'),
  ],
  sprawl: [
    require('@bryllim/workout-guide/assets/sprawl/frame-1.png'),
    require('@bryllim/workout-guide/assets/sprawl/frame-2.png'),
    require('@bryllim/workout-guide/assets/sprawl/frame-3.png'),
  ],
  'seal-jack': [
    require('@bryllim/workout-guide/assets/seal-jack/frame-1.png'),
    require('@bryllim/workout-guide/assets/seal-jack/frame-2.png'),
    require('@bryllim/workout-guide/assets/seal-jack/frame-3.png'),
  ],
  'cat-cow-stretch': [
    require('@bryllim/workout-guide/assets/cat-cow-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/cat-cow-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/cat-cow-stretch/frame-3.png'),
  ],
  'arm-circles': [
    require('@bryllim/workout-guide/assets/arm-circles/frame-1.png'),
    require('@bryllim/workout-guide/assets/arm-circles/frame-2.png'),
    require('@bryllim/workout-guide/assets/arm-circles/frame-3.png'),
  ],
  'worlds-greatest-stretch': [
    require('@bryllim/workout-guide/assets/worlds-greatest-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/worlds-greatest-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/worlds-greatest-stretch/frame-3.png'),
  ],
  'leg-swings-stretch': [
    require('@bryllim/workout-guide/assets/leg-swings-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/leg-swings-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/leg-swings-stretch/frame-3.png'),
  ],
  'torso-twist-stretch': [
    require('@bryllim/workout-guide/assets/torso-twist-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/torso-twist-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/torso-twist-stretch/frame-3.png'),
  ],
  'doorway-chest-stretch': [
    require('@bryllim/workout-guide/assets/doorway-chest-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/doorway-chest-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/doorway-chest-stretch/frame-3.png'),
  ],
  'childs-pose': [
    require('@bryllim/workout-guide/assets/childs-pose/frame-1.png'),
    require('@bryllim/workout-guide/assets/childs-pose/frame-2.png'),
    require('@bryllim/workout-guide/assets/childs-pose/frame-3.png'),
  ],
  'kneeling-hip-flexor-stretch': [
    require('@bryllim/workout-guide/assets/kneeling-hip-flexor-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/kneeling-hip-flexor-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/kneeling-hip-flexor-stretch/frame-3.png'),
  ],
  'hamstring-stretch': [
    require('@bryllim/workout-guide/assets/hamstring-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/hamstring-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/hamstring-stretch/frame-3.png'),
  ],
  'standing-quad-stretch': [
    require('@bryllim/workout-guide/assets/standing-quad-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/standing-quad-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/standing-quad-stretch/frame-3.png'),
  ],
  'seated-forward-fold-stretch': [
    require('@bryllim/workout-guide/assets/seated-forward-fold-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/seated-forward-fold-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/seated-forward-fold-stretch/frame-3.png'),
  ],
  'cross-body-shoulder-stretch': [
    require('@bryllim/workout-guide/assets/cross-body-shoulder-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/cross-body-shoulder-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/cross-body-shoulder-stretch/frame-3.png'),
  ],
  'wall-calf-stretch': [
    require('@bryllim/workout-guide/assets/wall-calf-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/wall-calf-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/wall-calf-stretch/frame-3.png'),
  ],
  'butterfly-stretch': [
    require('@bryllim/workout-guide/assets/butterfly-stretch/frame-1.png'),
    require('@bryllim/workout-guide/assets/butterfly-stretch/frame-2.png'),
    require('@bryllim/workout-guide/assets/butterfly-stretch/frame-3.png'),
  ],
};

/** Built-ins are illustrated; anything the user adds is not. */
export function exerciseArt(id: string): ExerciseFrames | undefined {
  return ART[id];
}

/** The still a list row shows. Frame 1 is the start of the movement. */
export function exerciseStill(id: string): number | undefined {
  return ART[id]?.[0];
}
